### PR TITLE
New features/settings, bit of bug fixes

### PR DESCRIPTION
**Pull request by henhouse**
Better and detailed descriptions in the commit messages. But I've fixed several bugs reported from users, as well as improved the overall functionality of the bot, and drastically stopped it from retweeting other bots that are retweeting fake contests or tweets in tweets of tweets (yea...).

Before this bot could tweet several thousand useless tweets that were often caused by many of these bots being confused by each other and tweeting around quoted tweets of other users. Almost every single one of these were completely invalid contests and not even real, just bad bot behavior. This has configurable checks now to make this bot more sophisticated with what it is tweeting, and lower down on it's chances of hitting the rate limits. It is now more likely to hit search rate API limit because it's having to search for new content because 99% of search results is invalid bot tweets and wants to search again quickly, so there is now 30 second sleep period between search queries.

With any luck, people using this bot will use these updates and trim down the amount of bad tweets out there so we can get better results as more bots stop retweeting garbage en-masse.

### CODE REVIEW

**Comment by qsypoq** [comment]
hi, i've done tests with your version, seems pretty good but i have an issue, when searching the word "retweet" no problem but it seems to be totally ignoring the "rt" keyword, any idea ?

**Comment by henhouse** [comment]
Hey there. Perhaps it's too short? That was the most annoying part to work with was the Twitter search queries. They can't be very long, and it's really difficult to run tests on them accurately. I was trying to do really large ones with multiple OR statements but it seems you can't really do that... That's why I have an array of search queries now that it just searches through.

Perhaps do not just do "rt" but like "rt to win", "rt 2 win", etc.

**Comment by raulrene** [comment]
Hi @henhouse , thanks for the dedicated work! I'm ashamed I haven't had time to improve on this Twitter bot, but it was a fun quick-do thing for me and I didn't think back then it would reach so many people. Glad someone finally had the time to also write some code. Hopefully I'll have a little more time in the near future to also put down some more code here.

Just a small thought: maybe keep the braces starting after the function definition instead of under it (Allman c++ style). And again, many thanks!

**Comment by henhouse** [comment]
@raulrene,

No worries, I had a bit of fun making improvements and making it more efficient. Some of the code isn't the best... but I don't often program in JavaScript and Node so it was a bit of practice for me to play around in. It seems like many people are probably using this bot, so I really wanted to make the improvements to not retweet other bots, block them, etc. because there's a incredibly high amount of useless bots retweeting each other... hah.

Isn't Allman style the way I did it? I always prefer brackets under function declarations out of habit... so I changed them all for my own personal readability. :grimacing:

**Pull request merged**
